export const GET_DETAIL_WORKER_PENDING = 'GET_DETAIL_WORKER_PENDING';
export const GET_DETAIL_WORKER_SUCCESS = 'GET_DETAIL_WORKER_SUCCESS';
export const GET_DETAIL_WORKER_FAILED = 'GET_DETAIL_WORKER_FAILED';

export const GET_DETAIL_RECRUITER_PENDING = 'GET_DETAIL_RECRUITER_PENDING';
export const GET_DETAIL_RECRUITER_SUCCESS = 'GET_DETAIL_RECRUITER_SUCCESS';
export const GET_DETAIL_RECRUITER_FAILED = 'GET_DETAIL_RECRUITER_FAILED';
